project:
  type: website
  output-dir: _site

lang: en

bibliography: references.bib
csl: chicago_custom.csl

website:
  title: "Computer Science Course Materials for School Year 2025/26   (2eW)"
  repo-url: https://github.com/SkriptenMk/I_eW_24-28
  repo-actions: [source, issue]
  repo-link-target: _blank
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Materials
        menu: 
        - text: Autumn Term 2024/2025
          href: files/HS_24.qmd
        - text: Spring Term 2025
          href: files/FS_25.qmd
        - text: Autumn Term 2025/2026
          href: files/HS_25.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-line-numbers: true
  pdf:
    pdf-engine: xelatex
    pdf-engine-opts:
      - -shell-escape
    fontsize: 11pt
    documentclass: scrartcl
    classoption: a4paper
    toc: false
    include-in-header: preamble.tex
    code-line-numbers: true 
    mainfont: "TeX Gyre Termes"
    monofont: "TeX Gyre Cursor"
